permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 12
comments: false
paginate_path: "/blog/page:num"

domain_name: m-core

safe:       false
port:       4000
## Used in older version of Jekyll
base-url:    ""
## Used in newer versions of Jekyll
baseurl:    ""

source:      .
destination: ./_site
exclude:
  - README.md
  - Rakefile
  - node_modules/
  - gulp/
  - bower
  - bower_components
  - config.rb
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js

name: Coin MAGI
title: Coin MAGI
meta_description: "Coin MAGI, cryptocurrency, Peer-to-Peer, Digital Currency"
meta_keywords: "MAGI, coin, crypto, currency, peer-to-peer, digital, payment"
url: http://www.m-core.org
production_url: http://www.m-core.org
repo: http://github.com/m-coin
disqus_shortname: "MAGI"
rss_path: .
url       : http://www.m-core.org
email     : contact@m-core.org
intro     : "MAGI is a peer-to-peer digital currency running constantly without downtime. MAGI coins are issued via personal devices without the need of interference by intermediary. MAGI focuses on fairness, cost effective and energy efficiency."

twitterofficial    : https://twitter.com/CoinMagi
twittermarketing   : https://twitter.com/Coin_Magi_XMG
facebook  : https://www.facebook.com/CoinMagi
github    : https://github.com/m-coin
reddit    : https://www.reddit.com/r/coinmagi
youtube    : https://www.youtube.com/user/TheCoinMagi
slack    : https://m-pays.slack.com

wallet_version: 1.4.4.1
wallet_url : http://coinmagi.org/bin
source_url_github : https://github.com/magi-project/magi

# Plugin: jekyll-assets
assets:
  dirname: /assets
  sources:
    - assets/img
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

